### ISSUE TITLE
$super 的调用

### ISSUE THREAD

**Issue by ystarlongzi** [rpkilby/vue-super#1]
```
......

methods: {
    hi: function () {
        // 法1：
        // this.$super();

        // 法2：
        // this.$super.hi();
    }
}

......
```

个人觉得『法1』更优雅些，不知博主怎么看？

另外，博主有了解过 Vue 为毛不支持 $super 的语法没

**Comment by rpkilby** [comment]
Hi @ystarlongzi. Sorry, I don't understand Chinese. Can you write in English instead? The best I can do is translate with Google.

Translated text:

> Personally feel "method 1" something more elegant, I do not know how bloggers look?
> 
> In addition, bloggers have understood the Vue for the hair does not support the $ super syntax

In response to the first sentence, I prefer the second syntax as it's more similar to python's  implementation of `super()`. Explicit is better than implicit. There are also cases where you may need to reference a different method on the parent class, and method 1 is unable to accommodate that. Additionally, method 2 is simpler to implement than method 1 :)

Unfortunately, I don't understand the second sentence.

**Comment by ystarlongzi** [comment]
Thank you!!!

The 1st sentence, the translate text is my mean, and i have get your idea. Thank your explain！

The 2nd sentence is mean

> Have blogger communicate with Vue author, about why Vue does not support $super syntax?

Now, i don't know whether you get my mean. My english is poor, especially speak and write.......

Thank you!!!

**Comment by rpkilby** [comment]
> Have blogger communicate with Vue author, about why Vue does not support $super syntax?

Not yet.

@yyx990803 - do you think this is worth adding to Vue? I could submit a PR w/ tests etc..

**Comment by rpkilby** [comment]
One additional thought - this only supports inheritance for methods, not for other handlers. eg, computed properties, event handlers, etc...

**Comment by yyx990803** [comment]
I don't really want to simulate full OO with Vue's extension system - I believe it results in less flexible systems overall. If possible I'd rather compose directly with mixins. So I guess my stance is not adding this to core.
