### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ijabit** [rpkilby/vue-super#2]
This is great! I can take all of my existing class based code and re-use it as Vue models. However, my project uses TypeScript and there is no definition for $super so I get this:
![image](https://user-images.githubusercontent.com/557752/37061196-ad5b8ad8-2160-11e8-8d31-054e26b6bd3e.png)

Now I read about module augmentation and how to use it with Vue here:
https://vuejs.org/v2/guide/typescript.html
![image](https://user-images.githubusercontent.com/557752/37061238-cdbc3f70-2160-11e8-9436-715e5511a2c7.png)

But I have to use the `any` type because the type for $super is dynamic. Is there any way to get the $super variable to be recognized as the parent class and get type safety and intellisense?

**Comment by rpkilby** [comment]
Hi @ijabit. I do not use Typescript, but my guess would be something like the following:

```typescript
import Vue from 'vue'

declare module 'vue/types/vue' {
    interface Vue {
        $super: Vue
    }
}
```

**Comment by rpkilby** [comment]
I'm also closing this, as I don't use Typescript and am not able to meaningfully provide help.

**Comment by ijabit** [comment]
That would be better than `any` but still wouldn't get me the parent's methods. Oh well, I guess I should be looking at using Mixins instead for Vue. I'll have to convert my code...

**Comment by rpkilby** [comment]
Does Typescript support type hinting? eg, could you provide a type hint in places where you call `$super`? Additionally, you might try to see how Typescript supports native `super()` calls, and see if you can somehow adapt that. 

Again, I don't use Typescript, so it's difficult for me to provide help.
